spring:
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
  kafka:
    consumer:
      auto-offset-reset: earliest
      max-poll-records: 500
      heartbeat-interval: 3000
      bootstrap-servers:
        - localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      group-id: funnel-test-v5
    listener:
      ack-mode: batch
      concurrency: 1
      type: batch
funnel:
  server:
    audit-center-topic: audit-center